###
# @name createAsset
POST http://localhost:3001/assets
Content-Type: application/json

{
  "name": "Amazon",
  "symbol": "AMZN",
  "price": 100,
  "image": "AMZN.png"
}
###
@assetId = {{ createAsset.response.body._id }}
###
GET http://localhost:3001/assets
###
GET http://localhost:3001/assets/AMZN
###
PATCH http://localhost:3001/assets/{{ assetId }}
Content-Type: application/json

{
  "name": "Amazon",
  "symbol": "NASDAQ: AMZN",
  "price": 100,
  "image": "AMZN.png"
}
###
DELETE http://localhost:3001/assets/{{ assetId }}


###
# @name createWallet
POST http://localhost:3001/wallets
###
@walletId = {{ createWallet.response.body._id }}
###
GET http://localhost:3001/wallets
###
GET http://localhost:3001/wallets/{{ walletId }}
###
DELETE http://localhost:3001/wallets/{{ walletId }}


###
# @name createWalletAsset
POST http://localhost:3001/wallets/{{ walletId }}/assets
Content-Type: application/json

{
  "shares": 69,
  "assetId": "{{ assetId }}"
}

###
# @name createOrder
POST http://localhost:3001/orders
Content-Type: application/json

{
  "walletId": "{{ walletId }}",
  "assetId": "{{ assetId }}",
  "shares": 10,
  "price": 100,
  "type": "BUY"
}
###
GET http://localhost:3001/orders?walletId={{ walletId }}